### ISSUE TITLE
Allow llines to be run with commands from stdin

### ISSUE THREAD

**Issue by memmerto** [MarcNo/lifelines#259]
Allow llines to be run with commands read from standard input. This would for example allow to call llines from a script to produce a set of reports without any user interaction.
# Benefits

1. automized testing of llines and reports!
2. automized script based creation of reports
3. use llines as a php-script on a website (hey, that's cool isn't it ;-?)
# Example

prompt&gt; llines -d DataBasePath &lt;myinput.lls

The file myinput.lls could look like this:
---- start of file ----
r
myreport
I1
testfile.ps
---- end of file ----

This would call "Create Report" from the main menu, enter "myreport" as the report name, answering the question for an individual to run the report for with "I1" and specify and output file as "testfile.ps". After creating the report lifelines should exit with a 0 code for no error or an error code if something went wrong.

Reported by: xorx

Original Ticket: "bugs/266":https://sourceforge.net/p/bugs/266

**Comment by disassembler** [comment]
It seems like `llexec` would be a better option here than using llines.

**Comment by memmerto** [comment]
llexec is designed solely for running reports on a given database.
The intent here is to be able to "script" UI commands so that we can automate various test activities.

**Comment by memmerto** [comment]
Not sure what I was thinking originally.  The example cited was for running a report, so llexec is the right tool for this.  This is how all of our tests are written.

Closing.
