### ISSUE TITLE
Error opening terminal: xterm

### ISSUE THREAD

**Issue by sviscapi** [MarcNo/lifelines#310]
Hi,

I have compiled LifeLines from git on the Open Pandora, an handheld computer running GNU/Linux (ARM):

https://pyra-handheld.com/boards/pages/pandora/

Unfortunately, starting "llines" (under XFCE 4.6.2 / Terminal 0.4.5) fails with the following error message:

Error opening terminal: xterm

What am I doing wrong ?

Best regards,

Sam a.k.a "Magic Sam" from the Open Pandora community

**Comment by memmerto** [comment]
Not a bug.  Closing.
